### ISSUE TITLE
Banner Images

### ISSUE THREAD

**Issue by wrightm1** [badhoc/MA2-Theme-Again#10]
I want to find new banner images, really not liking the current ones at all. I take it we're not using the page structure of the current blog and having pages just based on categories?

Maybe a site map is needed, unless we have one?

**Comment by badhoc** [comment]
![image](https://user-images.githubusercontent.com/18460697/41895748-b6d82d52-791a-11e8-9f31-4a71cf1b9289.png)

I pressumed that the 'site map' was jsut a super stripped down version of the current one ie jsut the categories then the other pages (about us, contact us, cookie policy) would be linked from the footer, with the 60second debt test as a linked out page?

Maybe a drawing is needed, I'm not sure if that makes sense or not!

**Comment by wrightm1** [comment]
We just need a photo for the top of each page. I'll source some cool new pics

**Comment by badhoc** [comment]
Hi @wrightm1  - can I get these pretty soon please
Pages we need banners for:

- [x] Homepage
- [x] Making Money
- [x] Saving Money
- [x] Budgeting
- [x] News
- [x] Living with Debt
- [x] Search
- [x] 404 Page Not Found
- [x] About
- [x] Contact
- [x] Worried about Money

**Comment by wrightm1** [comment]
Done, and inserted into the images folder

**Comment by badhoc** [comment]
Cheers for that mark - please coudl I have another spare for the top of the 'tag' pages [example](http://localhost/wordpress/tag/unemployment/)

I'll just put the same one on all of them, or I can put any of the above on there if you prefer?

**Comment by wrightm1** [comment]
Sure, can I do it this afternoon, I’m doing my java script stuff this morning ☺
