### ISSUE TITLE
Image Distortion on blog posts

### ISSUE THREAD

**Issue by badhoc** [badhoc/MA2-Theme-Again#14]
![image](https://user-images.githubusercontent.com/18460697/41896444-84fe4684-791c-11e8-8aed-7be67fef6255.png)

height/width properties seem to be off, check stylesheets.

**Comment by wrightm1** [comment]
I think I have an idea as to what this issue is but I can't really do anything without access to be able to develop the site. I'll picc this up once I get MAMP

**Comment by badhoc** [comment]
sorry fixed this one - will be uploaded in next commit
