### ISSUE TITLE
Shortcode for 60second test

### ISSUE THREAD

**Issue by badhoc** [badhoc/MA2-Theme-Again#2]
shortcode function set up in function.php
replace the return content to actually create the purple div w/text and button.

Must be responsive (stacked on mobile)

**Comment by wrightm1** [comment]
Got the code what do I do with it now? ;)

**Comment by badhoc** [comment]
Nice work @wrightm1 

So you want to:

- Clone the repository to your GitHub desktop. You now have a copy of the files on your pc.
- Create a Branch through GitHub Desktop to make your changes on.
- Edit the files with your new code (HTML to functions.php / add a sass module for the CSS)
- Push the Changes back to the github hosted repo

Let me know if you need help with any of the above.

**Comment by badhoc** [comment]
@wrightm1  [this page](http://localhost/wordpress/2018/05/made-redundant-how-to-pay-debt/) has the short code on if you want to add the html to the end of the functions.php file 

I've marked up where you need to change things (right at the end of the file)

**Comment by wrightm1** [comment]
I've added the CSS but think I added it to the master instead of creating a branch, ooops.

Want to check it's okay? And let me know where I put the HTML for the debt test.

Cheers

**Comment by wrightm1** [comment]
I believe this has been done and can be closed down? @badhoc

**Comment by badhoc** [comment]
I need to pull the changes into the master branch + tweak where needed. Will do today :+1:

**Comment by badhoc** [comment]
fixed on #31
