### ISSUE TITLE
Minor Styling / CSS Issues

### ISSUE THREAD

**Issue by badhoc** [badhoc/MA2-Theme-Again#20]
to be fixed / merged into Master as and when

*Numbers before headers:
    ![image](https://user-images.githubusercontent.com/18460697/41917322-061a61b4-7952-11e8-85fa-51d0af904498.png)

**Comment by badhoc** [comment]
Add ol styling needs checking what else it will affect.
    font-size: 1.15em;

**Comment by wrightm1** [comment]
That font looks like Corbel and the numbers in Corbel do that weird subscript thing

**Comment by badhoc** [comment]
yeah, it's not just that its the font size (as mentioned above) I just need to add that styling in somewhere then have a quick skim through the site to see if that change would affect anything else. 

NB not particularly a job for either of us, this is an on-going issue just so things don't get forgotten about.
