### ISSUE TITLE
Things that need changing on Staging /  Live

### ISSUE THREAD

**Issue by badhoc** [badhoc/MA2-Theme-Again#25]
### **Important**
These changes need to be made in the main wordpress settings, and cannot be updated through the theme. 
*Remember to amend them if rolling back at anytime*

 - Settings -> Reading -> Blog Posts Show at Most '7' *(going to write something in functions.php to change this on the category pages)*

**Comment by wrightm1** [comment]
When we eventually make this live are we essentially going to create a new WP site and apply this theme? This is why we need to remember some of these key WP settings? Sorry if I got confused

**Comment by badhoc** [comment]
No worries. We are just going to apply a new theme - but the site is going to be the same :) 

try logging in the staging site and changing the theme if you want?

**Comment by badhoc** [comment]
Widgets need updating
