### ISSUE TITLE
Search page needs styling

### ISSUE THREAD

**Issue by badhoc** [badhoc/MA2-Theme-Again#29]
Things to do

- [x] - take out moneyaware block
- [x] - take off category description
- [x] - add in search terms
- [x] - add in number of results
- [x] - add in search form
- [x] -styling
- [x] -check load more works

**Comment by badhoc** [comment]
![image](https://user-images.githubusercontent.com/18460697/42167219-41bc303c-7e05-11e8-9c20-63e7a78601c0.png)

@wrightm1  how do you want this styled?

**Comment by wrightm1** [comment]
I'll have a play and update soon

**Comment by wrightm1** [comment]
What do you think about the Search results returned being smaller, rather than the 3 column layout? @badhoc

**Comment by badhoc** [comment]
Can you add it as a new issue with low priority please?
Can look at it, but after functional stuff is done.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
