### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by badhoc** [badhoc/MA2-Theme-Again#3]
change the menu so it's editable from the backend ('Nav Menu')
add the class based on category
mobile design - burger

**Comment by badhoc** [comment]
burger added w/toggle display
@wrightm1 I left off the 'menu' text for now as it totally threw off the position of the x when it disappears on menu open. Not sure what you want me to do with it?

Also, are you wanting any mouse over effects on the menu? 

Still to do
 - add animation to menu open
 - fixed position menu *there's a weird gap issue going on with the header image*

**Comment by wrightm1** [comment]
Hya, the X close button doesn't look like it's evenly crossed. I'll explain this afternoon when we chat haha... Also do we need it to respond to the burger button at the particular break point it does? Would we want it to snap at a different rate? I'm just a beginner at this so I'm sure you'll have some logical explanation :)

**Comment by wrightm1** [comment]
Would I be able to add mist grey to the mobile menu background just to make it look more like a 'menu' not sure what your thoughts are?
