### ISSUE TITLE
Style returned search results

### ISSUE THREAD

**Issue by wrightm1** [badhoc/MA2-Theme-Again#35]
Reduce the size and increase the number of returned results on the search page.

**Comment by badhoc** [comment]
Any chance you can do a mockup for this please (mobile + desktop design) just a low-fidelity wireframe will do. 

I can adjust the number of posts to be displayed as a search result to 9 by default?

**Comment by badhoc** [comment]
Also I've removed the 'what is moneyaware' bit

**Comment by wrightm1** [comment]
Thinking about it, lets just display the results as they are now but display 9 items instead? Sound good?
