### ISSUE TITLE
Header image styling

### ISSUE THREAD

**Issue by wrightm1** [badhoc/MA2-Theme-Again#36]
Need to sort the scaling and cropping of the images.

**Comment by wrightm1** [comment]
![image](https://user-images.githubusercontent.com/40465896/42284455-7844ba20-7fa4-11e8-8acc-9b836ce74efc.png)

**Comment by wrightm1** [comment]
I'll create some CSS to style the search box to be on brand, infact I'll steal the code from the brand book site

**Comment by badhoc** [comment]
http://mkt00587/wordpress/category/budgeting/

If you visit my local environment you'll see the new images in place - Still working on getting them in the actual blog posts

@wrightm1 We also need a fallback image for the blog posts (square one) where a feature image hasn't been set.

**Comment by badhoc** [comment]
I've added a little bit of css to move the image position one mobile/desktop will push up to github now

**Comment by badhoc** [comment]
@wrightm1 Are you ok to finish this one off? 

Just ask if you need any help!

**Comment by wrightm1** [comment]
Not sure what I'm doing with this? Erg :)

**Comment by badhoc** [comment]
mobile devices fixed on next scout run - awkward stuff
