### ISSUE TITLE
Meeting - 10 Jul

### ISSUE THREAD

**Issue by badhoc** [badhoc/MA2-Theme-Again#40]
- [x] resize logo
- [x] add charcoal border to pages
- [x] 60-second needs hyphen, Take the test
- [ ] Sign-up needs styling through DNN
- [x] check border-radius
- [x] banner image size
- [x] border on top story
- [x] random through the images on archives when no featured image
- [x] Make image clickable on archive
- [x] Read more  correct case
- [x] Check banner on category
- [x] Check image size
- [x] pull in signifier for external links
- [x] take off category as tag
- [x] related posts three

**Comment by wrightm1** [comment]
Once I get the TFS access I need, hopefully today, I'll find the source code for the sign-up. I'll also source you a smaller logo.

**Comment by badhoc** [comment]
@wrightm1  please could you sort out some more images for those blog posts missing a featured image?
Also the signup styling needs doing when you finally get access.
Thanks.
