### ISSUE TITLE
Compiled SASS files create broken style.css sheet

### ISSUE THREAD

**Issue by wrightm1** [badhoc/MA2-Theme-Again#53]
Hi Becky, hope you're well? :)

When I make amends to the SASS files in the MonmeyAware theme and compile it produces a style sheet that breaks the homepage completely.

The style.css sheet that exists on this github site and that is compiled from the SASS doesn't work.

Did you make any changes to the live style.css sheet without using the SASS files and compiling them? I'm trying to work out how the current live style.css was compiled?

Cheers

Marky :)

**Comment by wrightm1** [comment]
Don't worry I manged to fix it.... There was an ID tag missing in the articles.scss file that was removing the tag from the style sheet when being compiled. I've added it back in. Phew xx

**Comment by badhoc** [comment]
Glad to hear you found the fix!
Anything you need just shout :)

Becky x

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
